// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiVYKIsV9Y8sHlyJ2askUZdELn_o2pzjc',
    appId: '1:1003006015211:web:23ba89a4f97cfc457b70ae',
    messagingSenderId: '1003006015211',
    projectId: 'kawaii-chat-app-firebase',
    authDomain: 'kawaii-chat-app-firebase.firebaseapp.com',
    storageBucket: 'kawaii-chat-app-firebase.appspot.com',
    measurementId: 'G-GFKXYRY5ZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmH6WFzJnF4zCJFkF3s1wLpQt8i7TilOo',
    appId: '1:1003006015211:android:a4a03943ca4fd3e37b70ae',
    messagingSenderId: '1003006015211',
    projectId: 'kawaii-chat-app-firebase',
    storageBucket: 'kawaii-chat-app-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5X2GBRX1n6IWG9QShR9xOXpjgmqZ6Vc4',
    appId: '1:1003006015211:ios:c05efc22ce486a457b70ae',
    messagingSenderId: '1003006015211',
    projectId: 'kawaii-chat-app-firebase',
    storageBucket: 'kawaii-chat-app-firebase.appspot.com',
    iosBundleId: 'com.example.kawaiiChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5X2GBRX1n6IWG9QShR9xOXpjgmqZ6Vc4',
    appId: '1:1003006015211:ios:c05efc22ce486a457b70ae',
    messagingSenderId: '1003006015211',
    projectId: 'kawaii-chat-app-firebase',
    storageBucket: 'kawaii-chat-app-firebase.appspot.com',
    iosBundleId: 'com.example.kawaiiChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiVYKIsV9Y8sHlyJ2askUZdELn_o2pzjc',
    appId: '1:1003006015211:web:713cbeb94673ab7f7b70ae',
    messagingSenderId: '1003006015211',
    projectId: 'kawaii-chat-app-firebase',
    authDomain: 'kawaii-chat-app-firebase.firebaseapp.com',
    storageBucket: 'kawaii-chat-app-firebase.appspot.com',
    measurementId: 'G-7H9WK74NDZ',
  );
}
